### ISSUE TITLE
🐞 PR 설정 액션이 멈추지 않음

### ISSUE THREAD

**Issue by kimyu0218** [boostcampwm2023/web09-MagicConch#549]
## Description
PR이 열리거나 수정되면 액션이 트리거되도록 했는데 PR을 설정하는 과정이 PR을 수정하는 작업이기 때문에 작업이 멈추지 않는다.

## How to reproduce it
```yaml
on:
  pull_request:
    types: ["opened", "edited"]
```

## Todo
`edited`를 삭제하여 PR이 열릴 때만 돌아가도록 수정
